baseURL = 'https://l3b4nk4.github.io/'
languageCode = 'en-us'
title = 'L3b4nk4'
theme = 'hugo-theme-reimu'
enableRobotsTXT = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[taxonomies]
tag = 'tags'
category = 'categories'

[outputs]
home = ["HTML", "RSS"]
